version: '3'

services:
  jupyter:
    image: quay.io/jupyter/pyspark-notebook:spark-3.5.3
    container_name: jupyter-notebook
    command: start-notebook.sh --NotebookApp.token=''
    ports:
      - "8888:8888" # Jupyter UI
      - "4040:4040" # Spark UI
    volumes:
      - "./mnt/:/home/jovyan/"
      - "./Data/:/home/jovyan/input/"
      - "./src/:/home/jovyan/input/"
      
    depends_on:
      - spark-master

  spark-master:
    image: bitnami/spark:3.5.0
    container_name: spark-master
    command: bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "7077:7077" # Spark Master Port
      - "8080:8080" # Spark Master Web UI
    environment:
      - SPARK_MODE=master

  spark-worker:
    image: bitnami/spark:3.5.0
    container_name: spark-worker
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-broker
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper